### ISSUE TITLE
Error with ctUplink podcast

### ISSUE THREAD

**Issue by dannykorpan** [mlj/castget#10]
Hi,
i've got following error with ctUplink podcast (https):
Updating channel ctUplink...
I/O warning : failed to load external entity "https://www.heise.de/ct/uplink/ctuplink.rss"
Error parsing RSS file https://www.heise.de/ct/uplink/ctuplink.rss.

**Comment by 0r0** [comment]
I'm getting the same error with a different podcast (running the latest FreeBSD port of castget):

Updating channel complete_privacy...
I/O warning : failed to load external entity "https://feeds.soundcloud.com/users/soundcloud:users:261098918/sounds.rss"
Error parsing RSS file https://feeds.soundcloud.com/users/soundcloud:users:261098918/sounds.rss.

The feed is valid:
https://validator.w3.org/feed/check.cgi?url=https://feeds.soundcloud.com/users/soundcloud:users:261098918/sounds.rss

**Comment by mlj** [comment]
Thanks, @0r0, for replicating!

I haven't had time to investigate this yet, but my guess here is that this has to do with https.

**Comment by 0r0** [comment]
You seem to be on the right track with your guess about https.  When I drop the 's' from 'https' in the url I get no such error and the episodes download as expected.

Thanks for this nice utility.
