### ISSUE TITLE
Podcast episodes overwritten due to name conflict

### ISSUE THREAD

**Issue by appel** [mlj/castget#13]
Thank you so much for castget, been happily using it for years!

Here's a podcast RSS feed that has the same name for each episode, causing castget to overwrite it.
[http://www.blogtalkradio.com/key-west-lou/podcast](http://www.blogtalkradio.com/key-west-lou/podcast)

It would be great to have an option for dynamically setting the filename with optional date and id3tag parameters to prevent this.

E.g.:

`[Tuesday Talk with Key West Lou]`
`url=http://www.blogtalkradio.com/key-west-lou/podcast`
`spool=/Podcasts/Tuesday Talk with Key West Lou`
`filename=key-west-lou-[YEAR][MONTH][DAY]-[HOUR][MINUTE]-[ID3TITLE].mp3`

**Comment by mlj** [comment]
*Basic* support (i.e. with quite limited parameters) for this has now been added (c337cc0152161db1c439dd28efc8745616dd1ee3).

**Comment by appel** [comment]
That's awesome! Thanks so much for your efforts, @mlj! Looking forward to seeing this expanded in the future.

**Comment by tonywhitmore** [comment]
That looks good, thank you!
