### ISSUE TITLE
Error parsing RSS file 

### ISSUE THREAD

**Issue by parkerlreed** [mlj/castget#14]
Arch x86_64
castget 1.2.2-1

Configuration
````
[df]
url=https://www.npr.org/rss/podcast.php?id=344098539
spool=/home/parker/Music/Podcasts
````

Command-line output
````
Updating channel df...
I/O warning : failed to load external entity "https://www.npr.org/rss/podcast.php?id=344098539"
Error parsing RSS file https://www.npr.org/rss/podcast.php?id=344098539.
````

**Comment by parkerlreed** [comment]
If I download the XML file and then say host it with python, it works. Seems to have an issue with the php serving up XML data.

**Comment by mlj** [comment]
It may be the same issue as in #10 which is caused by curl misbehaving with https.
