### ISSUE TITLE
Resume fails to continue correctly

### ISSUE THREAD

**Issue by leafhy** [mlj/castget#22]
**castget version 1.2.4**

Downloading each episode from 
http://podcast.npo.nl/feed/het-leven-een-gebruiksaanwijzing.xml took several attempts with
* castget --resume
* wget --continue
* firefox

Firefox and wget downloaded identical files.
Castget file sizes vary from smaller,larger and equal.

**Comment by mlj** [comment]
Thanks for the report. I can't reproduce this (by randomly downloading from this feed, interrupting the download and then restarting it).

Have you verified that the files downloaded by castget are actually broken? If you have configured castget to alter ID3 tags, the files may change size.

**Comment by leafhy** [comment]
I am using id3contenttype=Podcast.
Castget would stop downloading without manually interrupting it.

I used audacity to compare.
Castget downloaded the first half of the mp3 correctly and upon resuming shortened it.

The checksums for the castget downloaded files are different to firefox/wget.
So far this is the only podcast that has trouble downloading.

**Comment by mlj** [comment]
OK, thanks. So the checksums are irrelevant and the file size will go up/down when you use `id3contenttype=Podcast`.

Can you reproduce this behaviour or was it a one-off?

**Comment by leafhy** [comment]
I tried again and some of the mp3s downloaded ok, others that needed resuming failed to correctly download.

I interrupted and resumed one file and the size was correct but the audio was truncated. Castget previously downloaded file correctly without resume.

* Downloading 754849d80c48654a78387e12c704818b.mp3 (unknown length) from Het leven, een gebruiksaanwijzing
#############                                                               17%Error retrieving http://podcast.npo.nl/file/het-leven-een-gebruiksaanwijzing/754849d80c48654a78387e12c704818b.mp3: transfer closed with 25345413 bytes remaining to read
Error downloading enclosure from http://podcast.npo.nl/file/het-leven-een-gebruiksaanwijzing/754849d80c48654a78387e12c704818b.mp3.
----
I interrupted and resumed two more podcasts/episodes,
one resulted in being truncated.

The other podcast episode did resume correctly, this was a mono mp3 the others were stereo mp3.

**Comment by mlj** [comment]
This looks like intermittent connection issues somewhere between you and the web server and/or its resume functionality is flaky. castget uses curl to handle the downloading and doesn't actually do any that work itself, except writing the buffer to a file. The error message you see, `transfer closed` is from curl (error 18). Can you try using the curl command-line utility and see if it behaves in the same way? As it stands, there is very little to go on here...

**Comment by leafhy** [comment]
Thanks for your help, curl is the problem, not resuming properly is a "missing feature". Perhaps castget needs the option to use wget?
