### ISSUE TITLE
SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by appel** [mlj/castget#23]
I'm getting the following error when trying to download This American Life:

> SSL certificate problem: self signed certificate in certificate chain
Error downloading enclosure from https://www.podtrac.com/pts/redirect.mp3/podcast.thisamericanlife.org/podcast/618.mp3.

it seems to download a 1kb file.

Here's my config:

````
[This American Life]
url=http://feed.thisamericanlife.org/talpodcast
spool=/share/Multimedia/Podcasts/This American Life
id3leadartist=This American Life
````

I'm using version 1.2.4:

> [~] # castget --version
castget 1.2.4
with ID3 tag support
with --filter support
Copyright (C) 2005-2016 Marius L. Jøhndal <mariuslj at ifi.uio.no>

Hope you can help!

**Comment by mlj** [comment]
Can you try using curl directly from the command line? castget relies on curl to do all the heavy lifting involved in downloading so it's useful to know if it happens when you use it directly.

**Comment by appel** [comment]
Ah, that does seem to clarify things...

```
[~] # curl https://www.podtrac.com/pts/redirect.mp3/podcast.thisamericanlife.org/podcast/618.mp3
<html><head><title>Object moved</title></head><body>
<!-- pageview_candidate -->
<h2>Object moved to <a href="https://podcast.thisamericanlife.org/podcast/618.mp3">here</a>.</h2>
</body></html>
```

I assume there's no way to get around this since the redirect is coming straight from the feed (http://feed.thisamericanlife.org/talpodcast), right?

**Comment by appel** [comment]
That does seem to work.

````
[~] # curl -O -L https://www.podtrac.com/pts/redirect.mp3/podcast.thisamericanlife.org/podcast/618.mp3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   196  100   196    0     0   1439      0 --:--:-- --:--:-- --:--:--  1781
100 28.3M  100 28.3M    0     0  8976k      0  0:00:03  0:00:03 --:--:-- 9022k
````

I assume there's no way to directly pass curl flags through .castgetrc, is there?

**Comment by mlj** [comment]
No there isn't (and both those flags are in effect already set when castget invokes libcurl).

The certificate problem is a widely reported one (in various versions) and seems to either involve having outdated certificates on your system (and it seems they have recently been [updated](https://curl.haxx.se/docs/caextract.html)) or not having them at all/in a directory that libcurl doesn't expect.

I'm not entirely sure of the details of how libcurl decides on the location but it would be possible for castget to [override the location](https://curl.haxx.se/libcurl/c/CURLOPT_CAINFO.html), so I guess this is something that should be looked into in case people have the certificates in weird places.

(For the record, this works on my systems, ArchLinux + libcurl 7.54.0 and macOS Sierra + libcurl 7.51.0.)

**Comment by appel** [comment]
Gotcha, thanks @mlj. I'll investigate if my NAS has outdated certificates.

**Comment by mlj** [comment]
I'm closing this on the assumption that you managed to fix it. Feel free to re-open if the issue persists and you think it requires changes to castget (e.g. some kind of workaround that changes the behaviour of curl).
