### ISSUE TITLE
ID3 tags encoding

### ISSUE THREAD

**Issue by sprnza** [mlj/castget#29]
Hi there!
Thanks for the project, but I've stumbled upon a weird behavior. I try to use cyrillic characters in my ID3 tags like so:
```
 13 [aerostat]
 12 url=https://aerostatica.ru/podcast.xml
 11 spool=/home/speranza/Music/Podcasts/Аэростат
 10 id3album=Аэростат
  9 id3leadartist=Борис Гребенщиков
  8 id3comment=
  7 id3title=Аэростат
  6 
```
and the tags are being written^
```
srvr ➜  ~ id3info Music/Podcasts/Аэростат/707.mp3                                            

*** Tag information for Music/Podcasts/Аэростат/707.mp3                                      
=== TPE1 (Lead performer(s)/Soloist(s)): Борис Гребенщиков                                   
=== TIT2 (Title/songname/content description): Аэростат                                      
=== TALB (Album/Movie/Show title): Аэростат
=== TCON (Content type): Podcast
*** mp3 info
MPEG1/layer III
Bitrate: 320KBps
Frequency: 48KHz
```
but my neither my player nor Easytag app is being able to display the tags correctly:
![default](https://user-images.githubusercontent.com/1968839/49373342-d4682d00-f70e-11e8-9051-65f61877ecd9.png)

**Comment by mlj** [comment]
Hi, I think this is finally fixed. As of 6ad0c9d791f646e310b733a9d4d4f7797e92c79c, castget now uses taglib instead of id3lib to set the tags, which means that it deals properly with UTF-8 encoded strings.
