### ISSUE TITLE
castget did not download anything

### ISSUE THREAD

**Issue by raingloom** [mlj/castget#32]
this is my config:

```
[*]
spool=/home/raingloom/Podcasts/

[WelcomeToNightVale]
url=http://feeds.nightvalepresents.com/welcometonightvalepodcast

[GreaterBoston]
url=http://greaterboston.libsyn.com/rss

[AdventuresInNewAmerica]
url=http://feeds.nightvalepresents.com/adventuresinnewamerica

[AliceIsntDead]
url=http://feeds.nightvalepresents.com/aliceisntdeadpodcast

[WithinTheWires]
url=http://feeds.nightvalepresents.com/withinthewires

[OrbitingHumanCircus]
url=http://feeds.wnyc.org/orbitinghumancircus
```

when I ran `castget -vp WithinTheWires` it only printed `Updating channel WithinTheWires...` and did not download anything, I checked and my Podcasts folder is completely untouched

**Comment by Tomadz** [comment]
@raingloom I had a similar problem, but I'm pretty sure I found a fix. You need to find a folder which is named ".castget" and in it delete the XML files. When you've done that I would recommend running the command "castget -vp" which will give an oversight and progress bar on the file you are downloading.

**Comment by raingloom** [comment]
Nvm, I realized later that I need to specify the spool for each podcast separately, which was a hassle, so I just use greg now.

**Comment by mlj** [comment]
You don't need to specify a spool directory per podcast. There is a global section for this:

```
[*]
spool=/home/tom/podcasts

[scientific_american]
url=http://rss.sciam.com/sciam/science-talk
spool=/home/tom/podcasts/dsc
```

I know this is not super intuitive and it may be worth changing at some point.

**Comment by raingloom** [comment]
where does it download the podcast if I don't specify the spool directory for it, but only have a global definition?
