### ISSUE TITLE
wont compile for libxml2.9.3

### ISSUE THREAD

**Issue by timgray** [mlj/castget#33]
Checking for libxml is not allowing a far newer version to exist and fails.   configure needs to be fixed.

**Comment by mlj** [comment]
I don't understand what you mean by "not allowing a far newer version to exist". Can you expand on exactly what does not work?

I am building with libxml2 2.9.9 (with only that version of libxml2 installed), and that is fine.

**Comment by mlj** [comment]
Closing as there as been no update here for the past half year.
