### ISSUE TITLE
Error parsing RSS file /tmp/.NGNN9Z: Unrecognized top-level element feed

### ISSUE THREAD

**Issue by doronbehar** [mlj/castget#36]
I'm trying to hook castget with GitHub's releases atom feed. Does castget support atom feeds?

I get this error:

```
Updating channel sccache...
Error parsing RSS file /tmp/.T3419Z: Unrecognized top-level element feed.
```

When I define a channel such as:

```
[sccache]
url=https://github.com/mozilla/sccache/releases.atom
```

This error is both in branch master and the last release.

**Comment by mlj** [comment]
No, it doesn't support this type of feed.
