### ISSUE TITLE
Ronn: command not found

### ISSUE THREAD

**Issue by JoooostB** [mlj/castget#9]
Trying to make the file will result in the following error:

```
ronn --manual="User Commands" --organization="castget 1.2.1" --roff castget.1.ronn > castget.1
/bin/sh: ronn: command not found
```

**Comment by mlj** [comment]
Hi, you'll need to install [ronn](http://rtomayko.github.io/ronn/) if you want to rebuild the man pages. I've added a note about this in the README. There are prebuilt man pages in the distribution to avoid this dependency (along with ronn's dependencies).
